### PR TITLE
Add y1 states

### PR DESCRIPTION
**Pull request by phil-cork-epic**
This pull request adds the data and code for scraping, cleaning, and standardizing all year 1 (SFY23) states.

It also makes minimal structural changes to the dw-dashboard-app itself, so this should be specifically QA/QC'd before pushing to the production branch.

It also includes a new folder for analysis, a notebook for answering state-level questions about disadvantaged communities, and a script for more consistently transforming text into numeric columns.

### CODE REVIEW

**Review by EmmaLiTsai — COMMENTED** [review]
This looks great! I just had two minor notes in the dw-dashboard-app.R file, which might not need to be addressed before merging but I wanted to flag: 
- the app code is pulling dw-dashboard-data.csv, rather than dw-dashboard-data_v1-1.csv (which might be intentional for testing purposes, but wanted to flag)
- line 103: the use of `dplyr::across()` is deprecated - I think we can safely swap this line to: mutate(`Project Type` = str_replace(`Project Type`, 'Other', 'General'))

**Comment by phil-cork-epic** [comment]
>     * the app code is pulling dw-dashboard-data.csv, rather than dw-dashboard-data_v1-1.csv (which might be intentional for testing purposes, but wanted to flag)

Updated! Correct dataset is being pulled locally.

>     * line 103: the use of `dplyr::across()` is deprecated - I think we can safely swap this line to: mutate(`Project Type` = str_replace(`Project Type`, 'Other', 'General'))

Removed! All projects are categorized as "General" now rather than "Other" in the standardizing process, so this code was redundant.

**Review by EmmaLiTsai — COMMENTED** [review]
Another quick thing that I noticed while loading the new dataset in dw-dashboard-app.R: On line 499 (where we're rendering the ChartText output), the `pull(tooltip_text)` needs to be changed to `pull(Text)`. Otherwise, the pull function is pulling a data frame and the text doesn't show up when the app loads locally. 

So the final code for that chunk should be:   
```
output$ChartText <- renderText({
    req(input$ChartSelect)
    tooltip_text <- tooltip_text %>%
           filter(Name == as.character(input$ChartSelect)) %>%
           pull(Text)
  }) 
```

Will approve this PR after this switch!

**Comment by phil-cork-epic** [comment]
@EmmaLiTsai Chart text has been updated, good catch!

**Review by EmmaLiTsai — APPROVED** [review]
All PR-related comments resolved - woohoo!

**Pull request merged**
